services:
  db:
    image: postgres:18-alpine
    restart: unless-stopped
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres 
      POSTGRES_DB: gator
    ports:
      - "5433:5432"
    volumes:
      - postgres_gator_data:/var/lib/postgresql/data

volumes:
  postgres_gator_data:
